### ISSUE TITLE
Once I connect the pet shop to my wallet, every Adopt button turns into Success without me doing anything.

### ISSUE THREAD

**Issue by dennymrh** [truffle-box/pet-shop-box#46] opened 2019-05-09 02:42 UTC
Once I connect the pet shop to my wallet, every Adopt button turns into Success without me doing anything. Can @adrianmcli or anyone fix this? My repo is below: https://github.com/dennymrh/pet-shop-tutorial

**Comment by adrianmcli** [comment] 2019-07-15 08:35
I'm curious about this issue, let's re-open this. Either I or someone else will look at this sometime soon.

**Comment by dennymrh** [comment] 2019-07-15 13:12
Thanks Adrian

**Comment by adrianmcli** [comment] 2019-07-22 18:38
I am not able to reproduce your error. I even cloned your repo and ran it and it worked jus fine. Sorry, but I am going to close this issue again.

**Closed by adrianmcli** 2019-07-22 18:38 UTC
